Root/Users/urls.py
"""Users URLs."""

from django.urls import path
from Root.Users.views import LoginView, DashboardTemp, LogoutView

app_name = "users"
urlpatterns = [
    path("", view=LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path("dashboard/", view=DashboardTemp.as_view(), name="temp"),
    path("logout/", view=LogoutView.as_view(), name="logout"),
]

config/urls.py
"""
Project root urls
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("", include("Root.Users.urls", namespace="users")),
    # path("dashboard/", TemplateView.as_view(template_name="pages/home.html"), name="home"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

Root/Users/models/profiles.py
"""Profile model."""

# Django
from django.db import models
from django.utils.translation import gettext_lazy as _

# Utilities
from Root.utils.models import RootBaseModel


class Profile(RootBaseModel):
    """Profile model.

    User profile data
    A profile holds a user's public data like biography, picture,
    """

    user = models.OneToOneField("Users.User", on_delete=models.CASCADE)

    picture = models.ImageField(
        _("profile picture"), upload_to="users/pictures/", blank=True, null=True
    )
    biography = models.TextField(
        _("About your profile"),
        max_length=500,
        blank=True,
        help_text=_("A small biography about the user"),
    )

    def __str__(self):
        """Return user's str representation."""
        return str(self.user)

Root/Users/models/users.py
"""User model."""

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.core.validators import RegexValidator

# Utilities
from Root.utils.models import RootBaseModel


class User(RootBaseModel, AbstractUser):
    """User model.

    - Extend from Django's Abstract User, change the username field
      to email to make it unique.

    - The required fields are now username, first_name

    - The field phone_number is formatted by means of regular expressions

    - The new field is created is_client

    - The new field is created and by defauld is_verfied is set to
      false until it is verified by mail, in development it is shown
      in console-log(cli) and in production you have to send an email
    """

    email = models.EmailField(
        _("email address"),
        unique=True,
        error_messages={"unique": _("A user with that email already exists.")},
    )

    phone_regex = RegexValidator(
        regex=r"^\+?1?\d{9,15}$",
        message=_(
            "Phone number must be entered in the format: +999999999. Up to 15 digits allowed."
        ),
    )
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username", "first_name"]

    is_public = models.BooleanField(
        default=True, help_text=_("Public profiles show all information about users.")
    )

    is_verified = models.BooleanField(
        _("verified"),
        default=False,
        help_text=_(
            "Determine if an user has a verified account. "
            "Set to true when user verified its email address."
        ),
    )

    is_client = models.BooleanField(
        "client",
        default=True,
        help_text=(
            "Help easily distinguish users and perform queries. "
            "Clients are the main type of user."
        ),
    )

    def __str__(self):
        """Return username."""
        return self.username

    def get_short_name(self):
        """Function is overwritten and return username. Instead of first_name"""
        return self.username

Root/utils/models.py
# https://docs.djangoproject.com/en/3.2/topics/db/models/#model-inheritance

from django.db import models
from django.utils.translation import ugettext_lazy as _


class RootBaseModel(models.Model):
    """
    RootBase base model.
    This model act as abstract model and define fields that all others
    models in the application must to have.
    """

    created_at = models.DateTimeField(
        _("created at"),
        auto_now_add=True,
        help_text=_("Date time at which an object was created"),
    )
    updated_at = models.DateTimeField(
        _("updated_at"),
        auto_now=True,
        help_text=_("Date time at which an object was modified"),
    )

    class Meta:
        """Meta option."""

        # https://docs.djangoproject.com/en/3.2/ref/models/options/#available-meta-options
        abstract = True

        get_latest_by = "created_at"
        ordering = ["-created_at", "-updated_at"]

Root/Users/views.py
""" Users Authentication """

from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import View


class LoginView(auth_views.LoginView):
    """Login view."""

    template_name = "account/login.html"


class DashboardTemp(LoginRequiredMixin, View):
    """View of dashboard"""

    login_url = "/"
    # template_name = "pages/home.html"
    def get(self, request, *args, **kwargs):

        cntx = {
            "user": request.user,
        }
        return render(request, "pages/home.html", cntx)


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""

    template_name = "account/login.html"

Root/templates/401.html
{% extends "base.html" %}

{% block title %}Unauthorized (401){% endblock %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="text-center mt-4">
                        <h1 class="display-1">401</h1>
                        <p class="lead">Unauthorized</p>
                        <p>Access to this resource is denied.</p>
                        <a href="index.html">
                            <i class="fas fa-arrow-left me-1"></i>
                            Return to Dashboard
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </main>
<p>
{% if exception %}
{{ exception }}
{% else %}You're not allowed to access this page.{% endif %}
</p>
{% endblock content %}

Root/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="Sandbox Django" />
    <meta name="author" content="Rodolfo" />
    <title>{% block title %}MY TITLE{% endblock title %}</title>

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />

    {% block css %}
    <link
      href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css"
      rel="stylesheet"
    />
    <script
      src="https://kit.fontawesome.com/66253f90d2.js"
      crossorigin="anonymous"
    ></script>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    {% endblock %} {% block javascript %}
    <!-- {# Placed at the top of the document so pages load faster with defer #} -->
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
      crossorigin="anonymous"
    ></script>
    <script
      defer
      src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"
      crossorigin="anonymous"
    ></script>
    <script
      defer
      src="https://cdn.jsdelivr.net/npm/simple-datatables@latest"
      crossorigin="anonymous"
    ></script>
    <!-- My stuff: Third-party javascript libraries go here -->

    <!-- place project specific Javascript in this file -->
    <script defer defer src="{% static 'js/scripts.js' %}"></script>
    {% endblock javascript %}
  </head>
  <body class="sb-nav-fixed">
    
    {% block main_base %}
    {% endblock main_base %}

    {% block inline_javascript %}
    <!-- {# Script tags with only code, no src (defer by default) #} -->
    {% endblock inline_javascript %}

  </body>
</html>

Root/templates/pages/about.html
{% extends "base.html" %}

Root/templates/pages/home.html
{% extends "base.html" %} {% block main_base %}
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
  <!-- Navbar Brand-->
  <a class="navbar-brand ps-3" href="index.html">\,,/(^_^)\,,/</a>
  <!-- Sidebar Toggle-->
  <button
    class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0"
    id="sidebarToggle"
    href="#!"
  >
    <i class="fas fa-bars"></i>
  </button>
  <!-- Navbar Search-->
  <form
    class="
      d-none d-md-inline-block
      form-inline
      ms-auto
      me-0 me-md-3
      my-2 my-md-0
    "
  >
    <!-- Place to put elements to the left of the navbar button -->
    <!-- Place to put elements to the left of the navbar button -->
  </form>
  <!-- Navbar-->
  <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
    <li class="nav-item dropdown">
      <a
        class="nav-link dropdown-toggle"
        id="navbarDropdown"
        href="#"
        role="button"
        data-bs-toggle="dropdown"
        aria-expanded="false"
        ><i class="fas fa-user fa-fw"></i
      ></a>
      <ul
        class="dropdown-menu dropdown-menu-end"
        aria-labelledby="navbarDropdown"
      >
        <li><a class="dropdown-item" href="#!">Settings</a></li>
        <li><hr class="dropdown-divider" /></li>
        <li>
          <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
        </li>
      </ul>
    </li>
  </ul>
</nav>
<!-- Sidebar -->
<div id="layoutSidenav">
  <div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
      <div class="sb-sidenav-menu">
        <div class="nav">
          <div class="sb-sidenav-menu-heading">INDEX</div>
          <a class="nav-link" href="index.html">
            <div class="sb-nav-link-icon">
              <i class="fas fa-compress-arrows-alt"></i>
            </div>
            Dashboard
          </a>
          <div class="sb-sidenav-menu-heading">Interface</div>
          <a
            class="nav-link collapsed"
            href="#"
            data-bs-toggle="collapse"
            data-bs-target="#collapseLayouts"
            aria-expanded="false"
            aria-controls="collapseLayouts"
          >
            <div class="sb-nav-link-icon">
              <i class="fas fa-columns"></i>
            </div>
            Layouts
            <div class="sb-sidenav-collapse-arrow">
              <i class="fas fa-angle-down"></i>
            </div>
          </a>
          <div
            class="collapse"
            id="collapseLayouts"
            aria-labelledby="headingOne"
            data-bs-parent="#sidenavAccordion"
          >
            <nav class="sb-sidenav-menu-nested nav">
              <a class="nav-link" href="layout-static.html"
                >Static Navigation</a
              >
              <a class="nav-link" href="layout-sidenav-light.html"
                >Light Sidenav</a
              >
            </nav>
          </div>
        </div>
      </div>
      <div class="sb-sidenav-footer">
        <div class="small">Logged in as: {{ user.username }}</div>
        <span class="fs-6 text-break">{{ user.email }}</span>
      </div>
    </nav>
  </div>
  <!-- Sidebar -->
  <div id="layoutSidenav_content">
    <!-- 🚨 container 🚨 -->

    <p>PAGES > HOME -> CONTENIDO TEMP Y DISQUE RESTRINGIDO<></p>

    {% block content %} {% endblock content %}

    <!-- 🚨 /container 🚨 -->

    <footer class="py-4 bg-light mt-auto">
      <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
          <div class="text-muted">
            Made with <i class="fas fa-heart"></i> Website 2021
          </div>
          <div>
            <a href="#">Privacy Policy</a>
            &middot;
            <a href="#">Terms &amp; Conditions</a>
          </div>
        </div>
      </div>
    </footer>
  </div>
  <!-- /layoutSidenav_content -->
</div>
<!-- /layoutSidenav -->

{% endblock main_base %}

Root/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}

</div>
{% endblock content %}

Root/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}